config/routes.rb
Rails.application.routes.draw do
  root to: "classrooms#index"

  resources :classrooms do 
    member do
      get 'enroll'
      get 'enrolled'
    end

    collection do
      get 'my_classes'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    validates :name, presence: true
    validates :name, uniqueness: true
    
    before_destroy { users.clear }
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, authentication_keys: [:login]
  
  before_destroy { classrooms.clear }

  validates :fullname, :username, presence: true

  has_and_belongs_to_many :classrooms

  attr_writer :login

  def eligable_enroll(room)
    classrooms.where(id: room.id).blank?
  end

  def login
    @login || self.email || self.username
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    added_attrs = [:login, :email, :password, :password_confirmation, :remember_me, :fullname, :username]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  def index
    @classrooms = Classroom.all
  end

  def show
  end

  def new
    @classroom = Classroom.new
  end

  def edit
  end

  def create
    @classroom = Classroom.new(classroom_params)

    if @classroom.save
      redirect_to @classroom, notice: 'Classroom was successfully created.'        
    else
      render :new 
    end
    
  end

  def update
    if @classroom.update(classroom_params)
      redirect_to @classroom, notice: 'Classroom was successfully updated.' 
      render :show, status: :ok, location: @classroom 
    else
      render :edit 
    end    
  end

  def destroy
    @classroom.destroy
  
    redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.'       
  end

  def enroll
    current_user.classrooms << Classroom.find(params[:id])
    
    flash[:success] = 'Classroom was successfully enrolled'
    redirect_to root_path    
  end

  def enrolled
    @classroom = Classroom.find(params[:id])
    @users = @classroom.users
  end
  

  def my_classes
    @classrooms = current_user.classrooms
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message 
      end)
    end
    nil
  end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<%= form_with(model: classroom, local: true) do |form| %>
  <% if classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<div class="col-sm-12">
    <h1>Editing Classroom</h1>

    <%= render 'form', classroom: @classroom %>

    <%= link_to 'Show', @classroom %> |
    <%= link_to 'Back', classrooms_path %>
</div>

app/views/classrooms/enrolled.html.erb
<div class="col-sm-12">
  <h1>Enrolled students at <%= @classroom.name %></h1>

  <table class="table table-stripped table-bordered">
    <thead>
      <tr>
        <th>Fullname</th>
        <th>Username</th>
        
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.fullname %></td>
          <td><%= user.username %></td>          
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/classrooms/index.html.erb
<div class="col-sm-12">
  <h1>Classrooms</h1>

  <table class="table table-stripped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @classrooms.each do |classroom| %>
        <tr>
          <td><%= classroom.name %></td>
          <td><%= classroom.description %></td>
          <td><%= link_to 'Show', classroom %>
          <% if (!current_user.is_admin? && current_user.eligable_enroll(classroom)) %>
          | <%= link_to 'Enroll Now', enroll_classroom_path(classroom)  %>
          <% end %>
          | <%= link_to 'Enrolled Students', enrolled_classroom_path(classroom) %>          
          <% if current_user.is_admin? %>
            | <%= link_to 'Edit', edit_classroom_path(classroom) %>
            | <%= link_to 'Destroy', classroom, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Classroom', new_classroom_path if current_user.is_admin? %>

</div>

app/views/classrooms/my_classes.html.erb
<div class="col-sm-12">
  <h1>My Classrooms</h1>

  <table class="table table-stripped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @classrooms.each do |classroom| %>
        <tr>
          <td><%= classroom.name %></td>
          <td><%= classroom.description %></td>
          <td>
          <%= link_to 'Enrolled Students', enrolled_classroom_path(classroom) %>          
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Classroom', new_classroom_path if current_user.is_admin? %>

</div>

app/views/classrooms/new.html.erb
<div class="col-sm-12">
    <h1>New Classroom</h1>

    <%= render 'form', classroom: @classroom %>

    <%= link_to 'Back', classrooms_path %>
</div>

app/views/classrooms/show.html.erb
<div class="col-sm-12">
  <p>
    <strong>Name:</strong>
    <%= @classroom.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @classroom.description %>
  </p>

  <%= link_to 'Edit', edit_classroom_path(@classroom) %> |
  <%= link_to 'Back', classrooms_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyClass</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/shared/header' if user_signed_in? %>
    <div class="container">
      <div class="row">
        <div class="col-sm-12"><%= flash_messages %></div>        
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">MyClass</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Home <span class='sr-only'>(current)</span>".html_safe, root_path, class: 'nav-link' %>
      </li>
      <% unless current_user.is_admin %>
        <li class="nav-item">
          <%= link_to "My Classes", my_classes_classrooms_path, class: 'nav-link' %>
        </li>
      <% end %>
      
    </ul>
    <%= link_to "Logout", destroy_user_session_path, data: { confirm: "Are you sure?" }, method: :delete  %>
    
  </div>
</nav>